class PhantomJS():
	def __init__(self, executable_path:str) -> None: ...

	def get(self, uri:str) -> None: ...

	def find_element_by_id(self, element:str) -> 'PjsResult': ...

	def close(self) -> None: ...

class PjsResult():
	text = ''